buildConfiguration:
  buildCommand: npm run build:local
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
dynamicRedirects:
  # This is a rewrite because the status code is 200. It also takes advantage of built-in splat support.
  -
    from: /query/:color
    to: /:color?foo=bar
    status: 302
  -
    from: /grey/*
    to: /gray/:splat
    status: 200
  -
    from: /rewrite/:color
    to: /:color?rerouted=true
    status: 200
  -
    from: /redirect/*
    to: /:splat
    status: 303
  -
    from: /wow/:c
    to: /rewrite/:c
    status: 200
  -
    from: /*
    to: /nope/:splat
    status: 307
staticRedirects:
  -
    from: /grey-redirect
    to: /gray
    status: 308
  -
    from: /rewrite/red
    to: /orange
    status: 200
# adds authentication to your site. Commented out as a policy with the name auth02 must exist
# authentication:
#   policyName: auth02
#   includePaths:
#     - /red # red is locked down

